name: Python application

on:
  push:
    branches:
      - main  # Trigger the action when code is pushed to the `main` branch
  pull_request:
    branches:
      - main  # Trigger the action on pull requests to the `main` branch

jobs:
  test:
    runs-on: ubuntu-latest  # Use Ubuntu as the environment for running the job
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2  # Checkout the code in the repository
    
    - name: Set up Python
      uses: actions/setup-python@v2  # Set up Python environment
      with:
        python-version: '3.9'  # Use Python 3.9, or any version you prefer
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip  # Upgrade pip
        pip install -r requirements.txt  # Install dependencies if you have a requirements.txt file
        # If no requirements.txt, you can skip this line if no dependencies

    - name: Run tests
      run: |
        python -m unittest discover tests  # Run the unit tests in the `tests` directory
